### ISSUE TITLE
혹시 README.MD 내용 업데이트가 가능할까요?

### ISSUE THREAD

**Issue by OneTop4458** [taulmax/army_letter_macro#1]
안녕하세요 다름이 아니라 최근 군대 간 친구 인편을 보내주기 위해
Github를 뒤지던 중 이 프로젝트를 발견하였습니다

오늘 릴리스가 되었던데 
os 환경 변수 등록해주고 해야 하는 것 같던데 정확한 사용방법을 몰라서 
혹시 README.MD 업데이트가 가능할지 질문드립니다.

**Comment by taulmax** [comment]
죄송합니다 일이 급해서 열심히 일하다가 훈련소 갔다와버렸어요 ㅠㅠ

**Comment by taulmax** [comment]
현재는 ZUM 홈페이지 리뉴얼로 인해 고장난 상태입니다.
